
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    SentimentText = @"Thanks for the edit",
    //SentimentText = @"== OK! ==  IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!",
    LoggedIn = true,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");


Console.WriteLine($"Sentiment: {1F}");
Console.WriteLine($"SentimentText: {@"== OK! ==  IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!"}");
Console.WriteLine($"LoggedIn: {true}");


var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

